# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mktec.ui'
#
# Created: Tue May 10 19:29:58 2011
#      by: pyside-uic 0.2.8 running on PySide 1.0.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1049, 668)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1091, 631))
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.groupBox = QtGui.QGroupBox(self.tabWidgetPage1)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 1041, 621))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 1021, 561))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.search_article_number_lineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.search_article_number_lineEdit.setObjectName("search_article_number_lineEdit")
        self.horizontalLayout.addWidget(self.search_article_number_lineEdit)
        self.article_search_pushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.article_search_pushButton.setObjectName("article_search_pushButton")
        self.horizontalLayout.addWidget(self.article_search_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.article_number_label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.article_number_label.setObjectName("article_number_label")
        self.horizontalLayout_4.addWidget(self.article_number_label)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.article_name_label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.article_name_label.setObjectName("article_name_label")
        self.horizontalLayout_6.addWidget(self.article_name_label)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.article_graphicsView = QtGui.QGraphicsView(self.horizontalLayoutWidget)
        self.article_graphicsView.setObjectName("article_graphicsView")
        self.horizontalLayout_7.addWidget(self.article_graphicsView)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.article_price_label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.article_price_label.setObjectName("article_price_label")
        self.horizontalLayout_8.addWidget(self.article_price_label)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.re_trade_price_lineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.re_trade_price_lineEdit.setObjectName("re_trade_price_lineEdit")
        self.horizontalLayout_2.addWidget(self.re_trade_price_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.trade_quantity_lineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.trade_quantity_lineEdit.setObjectName("trade_quantity_lineEdit")
        self.horizontalLayout_3.addWidget(self.trade_quantity_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.node = QtGui.QLabel(self.horizontalLayoutWidget)
        self.node.setObjectName("node")
        self.verticalLayout.addWidget(self.node)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.trade_clear_pushButton_2 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.trade_clear_pushButton_2.setObjectName("trade_clear_pushButton_2")
        self.horizontalLayout_9.addWidget(self.trade_clear_pushButton_2)
        self.trade_update_pushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.trade_update_pushButton.setObjectName("trade_update_pushButton")
        self.horizontalLayout_9.addWidget(self.trade_update_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_21.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.trade_clear_pushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.trade_clear_pushButton.setObjectName("trade_clear_pushButton")
        self.verticalLayout_2.addWidget(self.trade_clear_pushButton)
        self.trade_article_tableWidget = QtGui.QTableWidget(self.horizontalLayoutWidget)
        self.trade_article_tableWidget.setObjectName("trade_article_tableWidget")
        self.trade_article_tableWidget.setColumnCount(3)
        self.trade_article_tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.trade_article_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.trade_article_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.trade_article_tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.trade_article_tableWidget)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_12 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.trade_total_label_2 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.trade_total_label_2.setObjectName("trade_total_label_2")
        self.horizontalLayout_10.addWidget(self.trade_total_label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_14 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        self.trade_payed_lineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.trade_payed_lineEdit.setObjectName("trade_payed_lineEdit")
        self.horizontalLayout_11.addWidget(self.trade_payed_lineEdit)
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.trade_discountrate_label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.trade_discountrate_label.setObjectName("trade_discountrate_label")
        self.horizontalLayout_11.addWidget(self.trade_discountrate_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.trade_check_pushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.trade_check_pushButton.setObjectName("trade_check_pushButton")
        self.horizontalLayout_12.addWidget(self.trade_check_pushButton)
        self.label_15 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        self.trade_over_label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.trade_over_label.setObjectName("trade_over_label")
        self.horizontalLayout_12.addWidget(self.trade_over_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.trade_save_pushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.trade_save_pushButton.setObjectName("trade_save_pushButton")
        self.verticalLayout_2.addWidget(self.trade_save_pushButton)
        self.horizontalLayout_21.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.tabWidgetPage2 = QtGui.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.horizontalLayoutWidget_6 = QtGui.QWidget(self.tabWidgetPage2)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(2, 6, 1031, 581))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.article_tableWidget = QtGui.QTableWidget(self.horizontalLayoutWidget_6)
        self.article_tableWidget.setObjectName("article_tableWidget")
        self.article_tableWidget.setColumnCount(3)
        self.article_tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.article_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.article_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.article_tableWidget.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_17.addWidget(self.article_tableWidget)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_17 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_5.addWidget(self.label_17)
        self.article_number_lineEdit_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.article_number_lineEdit_2.setObjectName("article_number_lineEdit_2")
        self.horizontalLayout_5.addWidget(self.article_number_lineEdit_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_18 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_13.addWidget(self.label_18)
        self.article_name_lineEdit_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.article_name_lineEdit_2.setObjectName("article_name_lineEdit_2")
        self.horizontalLayout_13.addWidget(self.article_name_lineEdit_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_19 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_14.addWidget(self.label_19)
        self.article_price_lineEdit_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.article_price_lineEdit_2.setObjectName("article_price_lineEdit_2")
        self.horizontalLayout_14.addWidget(self.article_price_lineEdit_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_20 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_15.addWidget(self.label_20)
        self.article_img_2_lineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.article_img_2_lineEdit.setObjectName("article_img_2_lineEdit")
        self.horizontalLayout_15.addWidget(self.article_img_2_lineEdit)
        self.imgfind_pushButton = QtGui.QPushButton(self.horizontalLayoutWidget_6)
        self.imgfind_pushButton.setObjectName("imgfind_pushButton")
        self.horizontalLayout_15.addWidget(self.imgfind_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.article_graphicsView_2 = QtGui.QGraphicsView(self.horizontalLayoutWidget_6)
        self.article_graphicsView_2.setObjectName("article_graphicsView_2")
        self.verticalLayout_3.addWidget(self.article_graphicsView_2)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.update_article_pushButton_2 = QtGui.QPushButton(self.horizontalLayoutWidget_6)
        self.update_article_pushButton_2.setObjectName("update_article_pushButton_2")
        self.horizontalLayout_16.addWidget(self.update_article_pushButton_2)
        self.delete_article_pushButton = QtGui.QPushButton(self.horizontalLayoutWidget_6)
        self.delete_article_pushButton.setObjectName("delete_article_pushButton")
        self.horizontalLayout_16.addWidget(self.delete_article_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tabWidgetPage2, "")
        self.tabWidgetPage3 = QtGui.QWidget()
        self.tabWidgetPage3.setObjectName("tabWidgetPage3")
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.tabWidgetPage3)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(12, 14, 1021, 571))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_21 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_18.addWidget(self.label_21)
        self.start_dateEdit = QtGui.QDateEdit(self.verticalLayoutWidget_4)
        self.start_dateEdit.setObjectName("start_dateEdit")
        self.horizontalLayout_18.addWidget(self.start_dateEdit)
        self.label_22 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_18.addWidget(self.label_22)
        self.end_dateEdit = QtGui.QDateEdit(self.verticalLayoutWidget_4)
        self.end_dateEdit.setObjectName("end_dateEdit")
        self.horizontalLayout_18.addWidget(self.end_dateEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_23 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_19.addWidget(self.label_23)
        self.search_tradenumber_lineEdit = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.search_tradenumber_lineEdit.setObjectName("search_tradenumber_lineEdit")
        self.horizontalLayout_19.addWidget(self.search_tradenumber_lineEdit)
        self.search_trade_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.search_trade_pushButton.setObjectName("search_trade_pushButton")
        self.horizontalLayout_19.addWidget(self.search_trade_pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)
        self.trade_history_tableWidget = QtGui.QTableWidget(self.verticalLayoutWidget_4)
        self.trade_history_tableWidget.setObjectName("trade_history_tableWidget")
        self.trade_history_tableWidget.setColumnCount(6)
        self.trade_history_tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.trade_history_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.trade_history_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.trade_history_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.trade_history_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.trade_history_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.trade_history_tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_4.addWidget(self.trade_history_tableWidget)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_20.addWidget(self.label_3)
        self.trade_number_label = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.trade_number_label.setObjectName("trade_number_label")
        self.horizontalLayout_20.addWidget(self.trade_number_label)
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_20.addWidget(self.label_8)
        self.trade_total_label = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.trade_total_label.setObjectName("trade_total_label")
        self.horizontalLayout_20.addWidget(self.trade_total_label)
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_20.addWidget(self.label_13)
        self.average_price_label = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.average_price_label.setObjectName("average_price_label")
        self.horizontalLayout_20.addWidget(self.average_price_label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.tabWidget.addTab(self.tabWidgetPage3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "交易信息", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">编码:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.article_search_pushButton.setText(QtGui.QApplication.translate("MainWindow", "查询", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">产品编号：</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.article_number_label.setText(QtGui.QApplication.translate("MainWindow", "Number", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">产品名称：</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.article_name_label.setText(QtGui.QApplication.translate("MainWindow", "name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">产品展示:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">单价：</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.article_price_label.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">交易单价:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">交易数目:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.node.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">事件通知</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.trade_clear_pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "删除", None, QtGui.QApplication.UnicodeUTF8))
        self.trade_update_pushButton.setText(QtGui.QApplication.translate("MainWindow", "更新", None, QtGui.QApplication.UnicodeUTF8))
        self.trade_clear_pushButton.setText(QtGui.QApplication.translate("MainWindow", "清空", None, QtGui.QApplication.UnicodeUTF8))
        self.trade_article_tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "编码", None, QtGui.QApplication.UnicodeUTF8))
        self.trade_article_tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "价格", None, QtGui.QApplication.UnicodeUTF8))
        self.trade_article_tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "数量", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">总额:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.trade_total_label_2.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">已付:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "折扣率：", None, QtGui.QApplication.UnicodeUTF8))
        self.trade_discountrate_label.setText(QtGui.QApplication.translate("MainWindow", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.trade_check_pushButton.setText(QtGui.QApplication.translate("MainWindow", "结帐", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">找零：</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.trade_over_label.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.trade_save_pushButton.setText(QtGui.QApplication.translate("MainWindow", "存档", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), QtGui.QApplication.translate("MainWindow", "交易", None, QtGui.QApplication.UnicodeUTF8))
        self.article_tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "编码", None, QtGui.QApplication.UnicodeUTF8))
        self.article_tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "名称", None, QtGui.QApplication.UnicodeUTF8))
        self.article_tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "单价", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "编码:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "名称:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "单价:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "产品展示:", None, QtGui.QApplication.UnicodeUTF8))
        self.imgfind_pushButton.setText(QtGui.QApplication.translate("MainWindow", "浏览", None, QtGui.QApplication.UnicodeUTF8))
        self.update_article_pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "更新", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_article_pushButton.setText(QtGui.QApplication.translate("MainWindow", "删除", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), QtGui.QApplication.translate("MainWindow", "产品", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "起始日期:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "结束日期:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "交易单号:", None, QtGui.QApplication.UnicodeUTF8))
        self.search_trade_pushButton.setText(QtGui.QApplication.translate("MainWindow", "查询", None, QtGui.QApplication.UnicodeUTF8))
        self.trade_history_tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "编码", None, QtGui.QApplication.UnicodeUTF8))
        self.trade_history_tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "名称", None, QtGui.QApplication.UnicodeUTF8))
        self.trade_history_tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "交易单号", None, QtGui.QApplication.UnicodeUTF8))
        self.trade_history_tableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "交易价格", None, QtGui.QApplication.UnicodeUTF8))
        self.trade_history_tableWidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "折扣率", None, QtGui.QApplication.UnicodeUTF8))
        self.trade_history_tableWidget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "数量", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "数目:", None, QtGui.QApplication.UnicodeUTF8))
        self.trade_number_label.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "总价:", None, QtGui.QApplication.UnicodeUTF8))
        self.trade_total_label.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "均价:", None, QtGui.QApplication.UnicodeUTF8))
        self.average_price_label.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage3), QtGui.QApplication.translate("MainWindow", "后台", None, QtGui.QApplication.UnicodeUTF8))

